---
# tasks file for kubernetes-ansible
- name: Include Prequisites
  ansible.builtin.include_tasks: prerequisites.yml

- name: Include Install task
  ansible.builtin.include_tasks: install.yml

- name: Include k8s-control-plane tasks
  ansible.builtin.include_tasks: control-plane.yml
  when: inventory_hostname in group['k8s-master']

- name: Include k8s-node tasks
  ansible.builtin.include_taks: node.yml
  when: inventory_hostname in group['k8s-worker']
