---
- name: Include containerd task
  ansible.builtin.include_tasks: containerd.yml

- name: Include swapoff task
  ansible.builtin.include_tasks: swapoff.yml

- name: Include Bridge Network task
  ansible.builtin.include_tasks: bridgenetwork.yml
